### ISSUE TITLE
Packaging module is not in requirements.txt file

### ISSUE THREAD

**Issue by alanakirby** [mstanislav/mrxcavator#3]
Running `python3 mrxcavator.py` for the first time after installing the requirements gives the error `packaging` is not installed. Once downloaded seperately, it works.

**Comment by mstanislav** [comment]
Thanks for letting me know, Alana. I've updated all of the dependency files, including requirements.txt, to reflect that and cut a new release today. Let me know if anything is still wonky on your end, otherwise should be all set. Appreciate it!
